### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by erlingur** [micwallace/WebPrint#1]
Hi!

I'm interested in this solution. How would I go about implementing this on my site?

I'm guessing I should host the WebPrint.jar file somewhere and change the url in the example.js file to that, then use pretty much the code in example.js?

Is that all I need to host? The jar file?

**Comment by micwallace** [comment]
Hey,

Yeah that's pretty much it, sorry for the lack of documentation. example.js may be a bit outdated.

I use it in my POS project, you might want to look over there (in /assets/js/print.js) for a more in depth example:
https://github.com/micwallace/wallacepos
https://wallacepos.com/

Cheers,
Michael

On 5 June 2015 1:02:06 AM AEST, "Erlingur Þorsteinsson" notifications@github.com wrote:

> Hi!
> 
> I'm interested in this solution. How would I go about implementing this
> on my site?
> 
> I'm guessing I should host the WebPrint.jar file somewhere and change
> the url in the example.js file to that, then use pretty much the code
> in example.js?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/micwallace/WebPrint/issues/1

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by erlingur** [comment]
Hi Michael

Thank you very much! I'll give it a shot, looks very interesting :)
