### ISSUE TITLE
how to implement to code igniter application?

### ISSUE THREAD

**Issue by TommyKing** [micwallace/WebPrint#2]
hello thanks for creating this, this might suit my POS application better, may i ask how to implement this to CI application? do i need java ?

thank you

**Comment by micwallace** [comment]
Hi Tommy,

No Java needed, simply use the javascript API (see example.js) and host 
the installer files on your sever.

Kind regards,
_Michael Wallace_
IT Consultant/Technician
https://wallaceit.com.au/ https://wallaceit.com.au
M:0410844700

**Comment by TommyKing** [comment]
i am facing issue in installing the shell script in linux. it seems to be corrupted
![screenshot from 2015-07-12 11 3a28 3a08](https://cloud.githubusercontent.com/assets/6888937/8636651/bff5ed60-2897-11e5-8bfd-bf191672c71a.jpg)
when i am using terminal mode
it give me 
gzip: sfx_archive.tar.gz: not in gzip format

I am sorry, but the installer file seems to be corrupted.
If you downloaded that file please try it again. If you
transfer that file with ftp please make sure that you are
using binary mode.

any chance you can uploading the sh?
seems like the sh is corrupted
this is the file md5sum
b7fdb1dfd8a6a84d48b2ea1160eac593

not the md5sum you provided 7e71fb860c9e361c34738ab6947b9a08

**Comment by micwallace** [comment]
Hi Tommy,

The installer is not an archive, it's a .sh shell script, you need to 
run it with bash, not the software-centre.
Bash is usually located at /bin/bash

If you are still having trouble you can find the shell script here:
http://content.wallaceit.com.au/webprint/WebPrint_unix_1_1.sh

Cheers,
Michael

**Comment by Jibigopi** [comment]
Hi
i try to install http://content.wallaceit.com.au/webprint/WebPrint_unix_1_1.sh
while installing im facing this error
![screenshot from 2015-07-12 21 10 42](https://cloud.githubusercontent.com/assets/3818825/8638508/4ccffc38-28db-11e5-9d22-fda413f1a3a3.png)

**Comment by micwallace** [comment]
Have you got Oracle Java installed? If not install it.
What version of Ubuntu are you using?

Can you send me the full error log at /home/%yourhome%/WebPrint/error.log ?

Also I'm interested to know what your POS application is and what your using as your existing printing solution?

Cheers,
Michael

**Comment by Jibigopi** [comment]
i have java and im using ubuntu 14.4

this is the error log 

java.lang.UnsatisfiedLinkError: Unable to load library 'appindicator': libappindicator.so: cannot open shared object file: No such file or directory
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:145)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:188)
    at com.sun.jna.Library$Handler.<init>(Library.java:123)
    at com.sun.jna.Native.loadLibrary(Native.java:255)
    at com.sun.jna.Native.loadLibrary(Native.java:241)
    at org.lantern.AppIndicatorTray.<clinit>(AppIndicatorTray.java:28)
    at webprint.Main.initSystemTray(Main.java:171)
    at webprint.Main.<init>(Main.java:68)
    at webprint.Main.main(Main.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
    at com.install4j.runtime.launcher.UnixLauncher.main(Unknown Source)

**Comment by micwallace** [comment]
Ah ok,
Looks like I need to bundle a library and change a few things around.

for the mean time you can run:
`sudo apt-get install libappindicator-dev`
in the terminal get it working.

I'm interested to know what your POS application is and what your using as your existing printing solution?

Cheers,
Michael

**Comment by Jibigopi** [comment]
Hi
Michael
thanks for your support 
actually we are developing one  pos with php codeigniter framework  
and im trying to implement your webprint on my sale receipt 

Thanks & Regards
jibi

**Comment by micwallace** [comment]
Yeah I found the website, very nice interface.
No worries, I'm glad your finding it useful :-D
If you need some ESC/P examples, you can look here:
https://github.com/micwallace/wallacepos/blob/master/assets/js/wpos/print.js

Cheers,
Michael

**Comment by Jibigopi** [comment]
thanks Michael

**Comment by Jibigopi** [comment]
Hi Michael
how can i implement with php 
can you guide me 

Thanks & Regards
Jibi
