### ISSUE TITLE
image file not printing

### ISSUE THREAD

**Issue by wolexzo07** [micwallace/WebPrint#6]
Admin please i added an image to print from an ESC/P printer but is printing the image src

**Comment by wolexzo07** [comment]
Please help with script that can print barcode or qrcode image from the esc/p printer

**Comment by micwallace** [comment]
Refer to the printer setup guides here:

Follow the below guide to setup a RAW printer:
https://qz.io/wiki/Setting-Up-A-Raw-Printer-in-Windows
https://qz.io/wiki/setting-up-a-raw-printer-in-osx
https://qz.io/wiki/setting-up-a-raw-printer-in-ubuntu-linux

**Comment by wolexzo07** [comment]
Please admin your reply does not solve my question because I already setup the printer but need the esc/p command to print image on the receipt.

**Comment by micwallace** [comment]
Ah ok, unfortunately webprint doesn't provide any of that functionality. However you can refer to the file here as an implementation guide:

https://github.com/micwallace/wallacepos/blob/master/assets/js/wpos/print.js

getESCPImageString is the function you're after, but it also has a lot of other useful ESCP commands.

**Comment by wolexzo07** [comment]
Thanks friend. More grease to your elbow

**Comment by wolexzo07** [comment]
good day friend, Please I need a simple example on how to add logo using
this function you sent me getESCPImageString

**Comment by micwallace** [comment]
No, Github issues are for application bugs, specific questions and feature ideas. It's not a forum for requesting free labour. Do it yourself or hire a programmer.

**Comment by wolexzo07** [comment]
Micwallace, I am also a programmer and I have done the other part of the
receipt and it working but the barcode file is what is not printing with
the receipt . Thank you
