### ISSUE TITLE
Cut is not working as expected

### ISSUE THREAD

**Issue by vijaythecoder** [micwallace/WebPrint#7]
I love what you have done so far, its working amazing and I found this after 2 days of research and using of plenty of plugins. You saved me.

I tried using your online demo and also example.html on my local environment, cut is not working. Any help would be highly appreciated. Thanks

**Comment by tresf** [comment]
@vijaythecoder stumbled upon this post... In my experience, this code works well for cutting.  Does it help?

```js
var esc_cut = "\x1B" + "\x69"; // cut paper
```

**Comment by vijaythecoder** [comment]
@tresf Thanks for the answer, yeah I figured it out. Thanks for the reply though 👍 
I am totally stuck on this( https://github.com/micwallace/WebPrint/issues/8 ) for more than 8 hours and found no solution https://github.com/micwallace/WebPrint/issues/8 could you help me this out please?

**Comment by tresf** [comment]
> @tresf Thanks for the answer, yeah I figured it out. Thanks for the reply though 

Can you please be more specific?  Did the above command fix your problem?

**Comment by vijaythecoder** [comment]
yes that works for cut paper. I am closing this issue. The following also works 
```javascript
    var esc_full_cut = '\x1B' + '\x69' // esc obsolute full (one point left) cut
    var esc_part_cut = '\x1B' + '\x6D' // esc obsolute partial (three points left) cut
    var gs_full_cut = '\x1D' + '\x56' + '\x30' // cut paper
    var gs_part_cut = '\x1D' + '\x56' + '\x31' // partial cut paper
```

@tresf Can you help me with issue https://github.com/micwallace/WebPrint/issues/8 ?
